# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'presentacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Presentacion(object):
    def setupUi(self, Presentacion):
        Presentacion.setObjectName("Presentacion")
        Presentacion.resize(564, 690)
        self.presentacion = QtWidgets.QLabel(Presentacion)
        self.presentacion.setGeometry(QtCore.QRect(0, 0, 561, 611))
        self.presentacion.setText("")
        self.presentacion.setPixmap(QtGui.QPixmap("presentacion.png"))
        self.presentacion.setScaledContents(True)
        self.presentacion.setObjectName("presentacion")
        self.pushButton = QtWidgets.QPushButton(Presentacion)
        self.pushButton.setGeometry(QtCore.QRect(400, 610, 151, 71))
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Presentacion)
        QtCore.QMetaObject.connectSlotsByName(Presentacion)

    def retranslateUi(self, Presentacion):
        _translate = QtCore.QCoreApplication.translate
        Presentacion.setWindowTitle(_translate("Presentacion", "Form"))
        self.pushButton.setText(_translate("Presentacion", "Continuar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Presentacion = QtWidgets.QWidget()
    ui = Ui_Presentacion()
    ui.setupUi(Presentacion)
    Presentacion.show()
    sys.exit(app.exec_())
